# Generated by Django 4.2.3 on 2023-12-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
