# Generated by Django 5.0 on 2023-12-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_productsrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
